services:
  jupyter:
    image: datascientistus/ds-python-env3
    platform: linux/amd64
    container_name: my-env
    ports:
      - "8888:8888"
    volumes:
      - ~/workspace/ml-learning-01_Foundations_Part_1:/work
    working_dir: /work
    tty: true